config/routes.rb
AmoebaCircusOnRailsRuby003::Application.routes.draw do
  root 'dashboard#index'
  get 'amoebas/:id/split' => 'amoebas#split', as: :split
  resources :acts
  resources :amoebas

end

app/models/act.rb
class Act < ActiveRecord::Base
  has_many :amoeba_acts   # an act may have many amoebas and vice versa
  has_many :amoebas, through: :amoeba_acts
end

app/models/amoeba.rb
class Amoeba < ActiveRecord::Base
  belongs_to :talent
  has_many :amoeba_acts # an amoeba may have many acts and vice versa
  has_many :acts, through: :amoeba_acts

  def act_ids=(act_ids)
    self.acts = Act.where(id: act_ids)
  end

  def divide
    @amoeba1 = Amoeba.create(
      name: Faker::Name.first_name, 
      generation: self.generation + 1, 
      talent: self.talent)

    @amoeba2 = Amoeba.create(
      name: Faker::Name.first_name, 
      generation: self.generation + 1, 
      talent: self.talent)

    self.acts.each do |act|
      act.amoebas << @amoeba1 << @amoeba2  # add the 2 new amoebas to all act of parent amoeba
    end
    self.destroy
  end
end

app/models/amoeba_act.rb
class AmoebaAct < ActiveRecord::Base
  belongs_to :amoeba
  belongs_to :act
end

app/models/talent.rb
class Talent < ActiveRecord::Base
  has_many :amoebas
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  before_action :set_act, only: [:show, :edit, :update, :destroy]

  # GET /acts
  # GET /acts.json
  def index
    @acts = Act.all
  end

  # GET /acts/1
  # GET /acts/1.json
  def show
  end

  # GET /acts/new
  def new
    @act = Act.new
  end

  # GET /acts/1/edit
  def edit
  end

  # POST /acts
  # POST /acts.json
  def create
    @act = Act.new(act_params)

    respond_to do |format|
      if @act.save
        format.html { redirect_to @act, notice: 'Act was successfully created.' }
        format.json { render action: 'show', status: :created, location: @act }
      else
        format.html { render action: 'new' }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acts/1
  # PATCH/PUT /acts/1.json
  def update
    respond_to do |format|
      if @act.update(act_params)
        format.html { redirect_to @act, notice: 'Act was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acts/1
  # DELETE /acts/1.json
  def destroy
    @act.destroy
    respond_to do |format|
      format.html { redirect_to acts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_act
      @act = Act.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def act_params
      params.require(:act).permit(:name, :date, :time)
    end
end

app/controllers/amoebas_controller.rb
class AmoebasController < ApplicationController
  before_action :set_amoeba, only: [:show, :edit, :update, :destroy, :split]

  # GET /amoebas
  # GET /amoebas.json
  def index
    @amoebas = Amoeba.all
  end

  # GET /amoebas/1
  # GET /amoebas/1.json
  def show
  end

  # GET /amoebas/new
  def new
    @amoeba = Amoeba.new
    @acts = Act.all
  end

  # GET /amoebas/1/edit
  def edit
    @acts = Act.all
  end

  # POST /amoebas
  # POST /amoebas.json
  def create
    @amoeba = Amoeba.new(amoeba_params)
    @amoeba.update(generation: 1)  # all new amoebas are 1st generation
    respond_to do |format|
      if @amoeba.save
        format.html { redirect_to @amoeba, notice: 'Amoeba was successfully created.' }
        format.json { render action: 'show', status: :created, location: @amoeba }
      else
        format.html { render action: 'new' }
        format.json { render json: @amoeba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amoebas/1
  # PATCH/PUT /amoebas/1.json
  def update
    @amoeba.acts.destroy_all if params[:amoeba][:act_ids] == nil
    respond_to do |format|
      if @amoeba.update(amoeba_params)
        format.html { redirect_to @amoeba, notice: 'Amoeba was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @amoeba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amoebas/1
  # DELETE /amoebas/1.json
  def destroy
    @amoeba.destroy
    respond_to do |format|
      format.html { redirect_to amoebas_url }
      format.json { head :no_content }
    end
  end

  def split
    @amoeba.divide
    redirect_to amoebas_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amoeba
      @amoeba = Amoeba.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amoeba_params
      params.require(:amoeba).permit(:name, :generation, :talent_id, act_ids: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/amoebas_helper.rb
module AmoebasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acts/_form.html.erb
<%= form_for(@act) do |f| %>
  <% if @act.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@act.errors.count, "error") %> prohibited this act from being saved:</h2>

      <ul>
      <% @act.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>
    <%= f.label :date, 'Date' %>
    <%= f.date_field :date %>
    <%= f.label :time, 'Time' %>
    <%= f.time_field :time %>
    <%= f.submit %>
  </div>
<% end %>

app/views/acts/edit.html.erb
<h1>Editing act</h1>

<%= render 'form' %>

<%= link_to 'Show', @act %> |
<%= link_to 'Back', acts_path %>

app/views/acts/index.html.erb
<h1>All Acts</h1>

<table cellpadding=7>
  <tbody>
      <tr>
        <td></td><td></td>
        <td><b>Name</b></td>
        <td><b>Date</b></td>
        <td><b>Time</b></td>
        <td><b>Amoebas</b></td>
      </tr>
    <% @acts.sort_by {|act| act.name}.each do |act| %>
      <tr>
        <td><%= link_to image_tag("pencil.png"), edit_act_path(act) %></td>
        <td><%= link_to image_tag('trash.png'), act, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to act.name, act, :class => "newlinkcolor" %></td>
        <td><%= act.date %></td>
        <td><%= act.time.strftime('%I:%M %P') %></td>
        <td><% act.amoebas.each_with_index do |amoeba, index| %>
              <%= amoeba.name %> 
              <% if index < act.amoebas.size - 1 %>
              |
              <% end %>
            <% end %>
        </td>
      </tr>
      <tr>

      </tr>
    <% end %>
    <br>
  </tbody>
</table>
<br>

<%= link_to 'New Act', new_act_path %>

app/views/acts/new.html.erb
<h1>New act</h1>

<%= render 'form' %>

<%= link_to 'Back', acts_path %>

app/views/acts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Act</h1>

<table cellpadding=7>
  <tbody>
      <tr>
        <td></td><td></td><td></td>
        <td><b>Name</b></td>
        <td><b>Date</b></td>
        <td><b>Time</b></td>
        <td><b>Amoebas</b></td>
      </tr>
      <tr>
        <td><%= link_to image_tag("pencil.png"), edit_act_path(@act) %></td>
        <td><%= link_to image_tag('trash.png'), @act, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to image_tag('back.png'), acts_path %></td>
        <td><%= @act.name %></td>
        <td><%= @act.date %></td>
        <td><%= @act.time.strftime('%I:%M %P') %></td>
        <td><% @act.amoebas.each_with_index do |amoeba, index| %>
              <%= amoeba.name %> 
              <% if index < @act.amoebas.size - 1 %>
              |
              <% end %>
            <% end %>
        </td>
      </tr>
      <tr>

      </tr>
    <br>
  </tbody>
</table>

app/views/amoebas/_form.html.erb
<%= form_for(@amoeba) do |f| %>
  <% if @amoeba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amoeba.errors.count, "error") %> prohibited this amoeba from being saved:</h2>

      <ul>
      <% @amoeba.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %><br>
    <%= f.label :talent, 'Talent' %>
    <%= f.select :talent_id, Talent.all.collect {|talent| [talent.name, talent.id]} %><br>


    <% @acts.each do |act| %>
      <%= check_box_tag "amoeba[act_ids][]", act.id, @amoeba.acts.include?(act) %>
      <%= label_tag :name, act.name %><br>
    <% end %> 
    <br>
    <%= f.submit %>
  </div>
<% end %>

app/views/amoebas/edit.html.erb
<h1>Editing amoeba</h1>

<%= render 'form' %>

<%= link_to 'Show', @amoeba %> |
<%= link_to 'Back', amoebas_path %>

app/views/amoebas/index.html.erb
<h1>All Amoebas</h1>

<table cellpadding=3>
  <tbody>
      <tr>
        <td></td>
        <td></td>
        <td><b>Name</b></td>
        <td><b>Gen</b></td>
        <td><b>Talent</b></td>
        <td><b>Acts</b></td>
      </tr>
    <% @amoebas.sort_by {|amoeba| amoeba.name}.each do |amoeba| %>
      <tr>
        <td><%= link_to image_tag("pencil.png"), edit_amoeba_path(amoeba) %></td>
        <td><%= link_to image_tag('trash.png'), amoeba, method: :delete %></td>
        <td><%= link_to amoeba.name, amoeba, :class => "newlinkcolor" %></td>
        <td><%= amoeba.generation %></td>
        <td><%= amoeba.talent.name %></td>
        <td><% amoeba.acts.each_with_index do |act, index| %>
              <%= act.name %> 
              <% if index < amoeba.acts.size - 1 %>
               |
              <% end %>
            <% end %>
        </td>
      </tr>
    <% end %>
    <br>
  </tbody>
</table>
<br>

<%= link_to 'New Amoeba', new_amoeba_path %>

app/views/amoebas/new.html.erb
<h1>New amoeba</h1>

<%= render 'form' %>

<%= link_to 'Back', amoebas_path %>

app/views/amoebas/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Amoeba</h1>

<table cellpadding=7>
  <tbody>
      <tr>
        <td><b>Name</b></td>
        <td><b>Gen</b></td>
        <td><b>Talent</b></td>
        <td><b>Acts</b></td>
      </tr>
      <tr>
        <td><%= @amoeba.name %></td>
        <td><%= @amoeba.generation %></td>
        <td><%= @amoeba.talent.name %></td>
        <td><% @amoeba.acts.each_with_index do |act, index| %>
              <%= act.name %> 
              <% if index < @amoeba.acts.size - 1 %>
              |
              <% end %>
            <% end %>
        </td>
      </tr>
      <tr>
        <td><%= link_to image_tag("pencil.png"), edit_amoeba_path(@amoeba) %></td>
        <td><%= link_to image_tag('trash.png'), @amoeba, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to image_tag('back.png'), amoebas_path %></td>
        <td><%= link_to image_tag('split.jpg', height: 60), split_path %></td>
      </tr>
    <br>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmoebaCircusOnRailsRuby003</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav>
      <%= link_to "Amoebas", amoebas_path, :class => "toplinkcolor" %> |
      <%= link_to "Acts", acts_path, :class => "toplinkcolor" %>
    </nav>
    
  <h1>Welcome to Raymoeba Circus!</h1>
<p>Please select from the choices above.</p>

<%= yield %>

</body>
</html>